### ISSUE TITLE
GPS isn't playing nice with tasks

### ISSUE THREAD

**Issue by nick-benoit14** [SmallSatGasTeam/errno_3#17]
The gps code must be calling some things that aren't very friendly with the freertos tasks. 

`````` delay(i);```
```malloc();``` 
```new()``` 

Don't play very nice with the tasks I don't think. We should investigate this. 
When it is called it will introduce nearly a second delay blocking all other tasks. 
``````

**Comment by Sailanarmo** [comment]
Ammon has fixed GPS, it is now working very nicely.
